/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/exoplanets.glb 
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/exoplanets-0938591d2f4c4172b09d9eb18ea480d7
Title: Exoplanets
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Exoplanets(props) {
  const { nodes, materials } = useGLTF('/exoplanets.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.772, -0.529, -0.241]} rotation={[-Math.PI, -0.8, -Math.PI]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Earth} scale={0.001} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Jupiter} position={[0.403, 0.38, 0]} scale={0.011} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Mars} position={[-0.422, 0.13, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Scale} position={[0, -1.186, 0]} />
    </group>
  )
}

useGLTF.preload('/exoplanets.glb')
