/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb 
Author: EV_car2013 (https://sketchfab.com/EV_car2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-space-black-16-free-6b46aa09dc4d4e90a79ea06f1d0aa719
Title: MacBook Pro M3 Space Black 16" Free
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Macbook(props) {
  const { nodes, materials } = useGLTF('/macbook.glb')
  // materials.EKmJncrpZQHBKDA.emissive.set('#ffffff')
// materials.EKmJncrpZQHBKDA.emissiveIntensity = 10

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.warzqlRACgPeAdi.geometry} material={materials.yJUdLgxNDNyUdxl} />
        <mesh geometry={nodes.rTtyYTHgLnhCqZu.geometry} material={materials.iWSqogxfhYyUIOb} />
        <mesh geometry={nodes.bstNWnZHIHOiyQO.geometry} material={materials.DGAqAZcSTHXTWuU} />
        <mesh geometry={nodes.yvMiyCYcEPcqtXy.geometry} material={materials.WhbMlpNvgcONgyj} />
        <mesh geometry={nodes.eydEmyVJQBjvdnh.geometry} material={materials.yJUdLgxNDNyUdxl} />
        <mesh geometry={nodes.qDLxqEaWnWqSnDi.geometry} material={materials.DGAqAZcSTHXTWuU} />
        <mesh geometry={nodes.PSLtXtWDWVhCixX.geometry} material={materials.baUHMuvZrSHBvQt} />
        <mesh geometry={nodes.zeWbFFuMiZmeXxp.geometry} material={materials.qUSlVOADZiDOKeA} />
        <mesh geometry={nodes.wfXwnOFmiuWPUdm.geometry} material={materials.EEMKPfeJLVEnvvr} />
        <mesh geometry={nodes.tZJqdqSVGqOgsic.geometry} material={materials.RMKjvllDyhhTZCT} />
        <mesh geometry={nodes.eLlwDiAlDquFgeM.geometry} material={materials.zKouxBFfApApXTS} />
        <mesh geometry={nodes.oLzRxOeMrSLxSmk.geometry} material={materials.WfxRKlizUQDauQm} />
        <mesh geometry={nodes.TCByPQZKwVqqiFh.geometry} material={materials.qUSlVOADZiDOKeA} />
        <mesh geometry={nodes.jVrhNiVzIJhZgCA.geometry} material={materials.baUHMuvZrSHBvQt} />
        <mesh geometry={nodes.GHvdcAIJlsfPODX.geometry} material={materials.AHwvtxwrxLKtYMU} />
        <mesh geometry={nodes.XvxgyKVhxautUcy.geometry} material={materials.GalaiBraRuKoCfq} />
        <mesh geometry={nodes.pCGdiVczxYXeXmL.geometry} material={materials.RMKjvllDyhhTZCT} />
        <mesh geometry={nodes.jVrhNiVzIJhZgCA_0.geometry} material={materials.jVrhNiVzIJhZgCA_0} />
        <mesh geometry={nodes.UiXFczJaHFDdCaO.geometry} material={materials.YfnURoAbKKuXatK} />
        <mesh geometry={nodes.eAImcjAPuIvzZaT.geometry} material={materials.IVIPagaCeZKrLGG} />
        <mesh geometry={nodes.axTrrRBMcNJpKPU.geometry} material={materials.eCZcaWbIDAENVlw} />
        <mesh geometry={nodes.gQWCCUjywjQssui.geometry} material={materials.UqZzTGJBLaUGErr} />
        <mesh geometry={nodes.YzeqtwxgNxPyiPq.geometry} material={materials.IPTIHYzeXzLGbph} />
        <mesh geometry={nodes.FuwIEgGDxyjBwSk.geometry} material={materials.fkwfGoiyRwUtiJt} />
        <mesh geometry={nodes.FZmjAFRSRDggwYJ.geometry} material={materials.naaiKhdhpsagCKi} />
        <mesh geometry={nodes.MKkQsweMigSOunp.geometry} material={materials.lCqpvQHnwKohyfX} />
        <mesh geometry={nodes.DqfqMMwZhGPqnwX.geometry} material={materials.bTJASKVBIrXIRaL} />
        <mesh geometry={nodes.yeokUYzNPWAIXeJ.geometry} material={materials.dcXlIurUtHkwnUY} />
        <mesh geometry={nodes.IMHPyHDOJxkXEva.geometry} material={materials.dcXlIurUtHkwnUY} />
        <mesh geometry={nodes.QIkDbSisNVJgKLq.geometry} material={materials.kmbRCEUXlOtVIqy} />
        <mesh geometry={nodes.usPYSfTIKUreWzn.geometry} material={materials.hnFcpQSrnVUEbOw} />
        <mesh geometry={nodes.phWqrkjulCawhQa.geometry} material={materials.naqClwBwNdmaheo} />
        <mesh geometry={nodes.yMUBkewdnioVQiE.geometry} material={materials.UQVNvWjWQqpJDDR} />
        <mesh geometry={nodes.pZAIwbmwDyABQoB.geometry} material={materials.UQVNvWjWQqpJDDR} />
        <mesh geometry={nodes.LFLQMgXzTpUrWpV.geometry} material={materials.vBJBKHXODRWbIgV} />
        <mesh geometry={nodes.eqgQimthTNCrEJx.geometry} material={materials.uCrXQLRidcCpTQM} />
        <mesh geometry={nodes.uTnLeivQYhrAurO.geometry} material={materials.uCrXQLRidcCpTQM} />
        <mesh geometry={nodes.VZgnQYgnZcbxbxy.geometry} material={materials.UQVNvWjWQqpJDDR} />
        <mesh geometry={nodes.TsFhBHgIPBrFNhY.geometry} material={materials.UQVNvWjWQqpJDDR} />
        <mesh geometry={nodes.sgvWtynSmRsjzHw.geometry} material={materials.UQVNvWjWQqpJDDR} />
        <mesh geometry={nodes.RVxkkNdkMEFfNQf.geometry} material={materials.MaLPEVacYvldCRk} />
        <mesh geometry={nodes.jbeGrjfMvrxUgkT.geometry} material={materials.ghrcUbCACoBOerj} />
        <mesh geometry={nodes.WzrsrlSrZduxPgX.geometry} material={materials.ztVcYLlDuxQtPHD} />
        <mesh geometry={nodes.KrLfyfKwdrgNPjA.geometry} material={materials.pnedyDcOzcuoUpY} />
        <mesh geometry={nodes.DKKOjwdknHPcNAv.geometry} material={materials.QCeNLQBkihAgGOT} />
        <mesh geometry={nodes.BdvamLfMOiXahIz.geometry} material={materials.fKgKqoPBEFjoSwi} />
        <mesh geometry={nodes.SpcJsGTUtkIkhJG.geometry} material={materials.gizMuitlIkLsCSR} />
        <mesh geometry={nodes.KiqAGoiMITVbhxa.geometry} material={materials.ejwEbWcNpVgOGyS} />
        <mesh geometry={nodes.FZbqQzcfpysbCaX.geometry} material={materials.EKmJncrpZQHBKDA} /> 
        
        <mesh geometry={nodes.MHEnotqPFqTgnQZ.geometry} material={materials.DTtyFpSjtoSKNpU} />
        <mesh geometry={nodes.qwwokHPVzHCeTNP.geometry} material={materials.lVkwMMCVnyMWEui} />
        <mesh geometry={nodes.qbCowwAEXmMwXKI.geometry} material={materials.naaiKhdhpsagCKi} />
        <mesh geometry={nodes.eVdSUYIqmtLvNwc.geometry} material={materials.xelfFIHMTwrMhxW} />
        <mesh geometry={nodes.oKHiHzUAFfMmOOH.geometry} material={materials.lCqpvQHnwKohyfX} />
        <mesh geometry={nodes.WKURUXXuVLbXuse.geometry} material={materials.MaLPEVacYvldCRk} />
        <mesh geometry={nodes.jKXKpAmgmNCgcwB.geometry} material={materials.UQVNvWjWQqpJDDR} />
        
      </group>
    </group>
  )
}

useGLTF.preload('/macbook.glb')
